language: node_js
node_js:
- '0.10'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: XIg4GLdXUnXYWuLf/r3SjN4X9gnZyP4vHSpEj57JXv7MZqfTb+BNLjVy10e9vHNZ6uOStwuBuBwlW1xO3KCtjt2fS/NjQNsp2nFn28p4rxbHUQys/hsOiOS30JaXoOLBbraPOIduyuwHS/Z9mPf7+RsC0xe+x7DMhIzFvTXNYf8LYT6cu16L2F9aqIFDFbTONJSyNLpsR+UxecxkxRIobrb2K7KzNsZN3SAnlvfR26tP2jJ2OyEJTYirZP3Eyii22oAn33OFf/q+6Gty5ia8xo8pWSVzW1fzz6V9uUBFQh9U0vmG+592yVWf7nc2PihadHAkI3aoPjovI3c5ys5Ej9TnbaXngI4XDmwQmWICtEMnZ7bXnfecU0TkSsyY3MNmGFI4vOcMS+EbqWW/9a7ltuv+sPdlYNiNSbnd3h1eYtLLEhN81BECDpUirz9HTwKGL9UYs9ui6/DGbwvFx+3zd/NWuMs/NOMFMeAC5x/UJs2/TRBfk39gSctn9u11mY54RI7P59VUR/j7uxbhlya4Nl2ADw9YKQqCkVQmroSwAzQoz4gfclU1L2x/uML0eCypMWA6wofE34uS8iWBYzNb82iK/MEbRBf3A7dGAxGIJO5xNcwlWwdO0jk2b/wNVC32vqVNWWFL1C9PWP7oxc9WOSpMKC0CPR6y1jDaaYIbDVo=
  on:
    tags: true
    repo: angular-ui/ui-indeterminate
