language: node_js
node_js:
- '0.10'
git:
  depth: 10
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower gulp-cli
- npm install -q
- bower install --force
- bower install --force
script: gulp
deploy:
  provider: npm
  email: adrien.crivelli@gmail.com
  api_key:
    secure: cGU87j+vxqfNrdmpJG3+jOze0GIN4ovyw7A0iOz8GlFR19tnSq8rKmK0Md5/DYBrSIa6gMSQLikv/TDDCnV14EujTL4I3Gp2HjFgcHRVL8fs60QBubbxNttvZNlQppSzSM0sGTYgJR2tUw1yCFMCrxp2nSOFlaz2/0OGIpw7IxUgC2nQ4F+BnJZsw/yI16IDrZv8sRD40/munRa0/voOJZfwdr2EAJtocDbmKjPoKYdmeNJw26O9jujfGkhWrAH/UuJ6tkVYHgQqKY8rmTLJJCWsGw8jqbwr5n3XhQ6t4gsGePhRTgmOOiWk5GlggBOOTSnW1xcCLlK2S7VR9d8QnkZsZcsf3WK0hivOqH0zge86M9F6drQgFTQNT5Jn9P0MFL4jCBWDq85F3sRtvxLx16SF7mOy99Mou/QhMF/o2if9Yeyi6Bi00i2VKiUH6+AOYIj7wYNi2nbytaOibWRx8jy5GsP2f3Cxv6aMfBfS4inxatu+nkIQCFRoSWFd3Zf954s+uqj4FD1tYV+ie8+waOLaLEq+XujGmLBuMynOMWVE5TtntT52dvch+v2k1ELwsPf5WJLi9ufxZZy0iGNx8Du0OWR9Qj03CeZyjlBrnu0Lb05OtPn+53LEcQAKexFTCZ3NeM7eR4chY8qbcmSGfk5AHRG8nLlTT/T4gFSpFBU=
  on:
    tags: true
